### PR TITLE
 Update dependencies, added auto-discover, fixed autoload

### PR DESCRIPTION
**Pull request by nasrulhazim**

### CODE REVIEW

**Comment by rabin-io** [comment]
@llaiajiale please consider merging this PR as I had to do the same changes on my fork to allow it to work with recent Laravel (5.8)  and Lumen.

I also have more patch's which like to publish upstream, e.g support for Doctrine\DBAL which provide more DB options.

**Comment by nasrulhazim** [comment]
@rabin-io you may refer to my blog [post](https://blog.nasrulhazim.com/2019/08/laravel-informix-db/) if you want to use the package now. Tested with Laravel 5.8, it works and I will update to support Laravel 6.0 as well.

**Comment by rabin-io** [comment]
thx @nasrulhazim as you did I had to fork and update the repo my self once (see [here](https://blog.rabin.io/sysadmin/laravel-lumen-informix)), and it seems you had to resolve the same issues as I did. so this is why I'm asking @llaiajiale to approve the PR and push the changes upstream and make them available for every one, as this is the first repo you find when you look for informix + laravel.

**Comment by nasrulhazim** [comment]
@rabin-io , I have added for Laravel 6.0 Support.

So in this PR includes Laravel 5.8 and Laravel 6.0 as well. You may want to test it on your environment.

**Comment by rabin-io** [comment]
Thanks I see, 

you should probably diff your fork with mine and see if there any thing you can benefit from as well, and reduce the diff to the upstream between our forks.

**Pull request closed without merging**
